export const mockProducts = [
  {
    id: 1,
    prodname: "Embroidered Long Sleeve Sports Shirt",
    price: 6820,
    originalPrice: 8830,
    image: "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
      "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/30220263/2024/7/14/84aa150c-3151-4513-9424-1150f99656211720935744276FREECULTRMen2HoodedOrganicCottonPocketsT-shirt1.jpg",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Collared",
    pattern: "Embroidered",
    rating: 4.8,
    reviews: 127,
    description:
      "A high-quality embroidered long sleeve shirt suitable for sports occasions.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Emerald", "Green", "Gray"],
    inStock: true,
  },
  {
    id: 2,
    prodname: "Checked Sleeveless Casual Shirt",
    price: 7849,
    originalPrice: 9065,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "Round Neck",
    pattern: "Checked",
    rating: 4.0,
    reviews: 128,
    description:
      "A high-quality checked sleeveless shirt suitable for casual occasions.",
    sizes: ["XS", "XL", "XXL", "M", "S", "L"],
    colors: ["Gold", "Silver", "White"],
    inStock: true,
  },
  {
    id: 3,
    prodname: "Striped Short Sleeve Ethnic Shirt",
    price: 5628,
    originalPrice: 7883,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    ],
    category: "men",
    sleeveType: "Short Sleeve",
    neckType: "V-Neck",
    pattern: "Striped",
    rating: 4.0,
    reviews: 295,
    description:
      "A high-quality striped short sleeve shirt suitable for ethnic occasions.",
    sizes: ["XS", "S", "M", "XL", "L", "XXL"],
    colors: ["Pink", "Blue", "Emerald"],
    inStock: true,
  },
  {
    id: 4,
    prodname: "Checked Sleeveless Formal Shirt",
    price: 4396,
    originalPrice: 5609,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "Round Neck",
    pattern: "Checked",
    rating: 4.6,
    reviews: 239,
    description:
      "A high-quality checked sleeveless shirt suitable for formal occasions.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Gray", "Pink"],
    inStock: true,
  },
  {
    id: 5,
    prodname: "Solid Boat Neck Ethnic Shirt",
    price: 5210,
    originalPrice: 7876,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "Boat Neck",
    pattern: "Solid",
    rating: 4.2,
    reviews: 62,
    description:
      "A high-quality solid sleeveless shirt suitable for ethnic occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Maroon", "Royal Blue", "Black"],
    inStock: true,
  },
  {
    id: 6,
    prodname: "Printed Long Sleeve Party Shirt",
    price: 6159,
    originalPrice: 7655,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Collared",
    pattern: "Printed",
    rating: 4.5,
    reviews: 177,
    description:
      "A high-quality printed long sleeve shirt suitable for party occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "White", "Black"],
    inStock: true,
  },

  {
    id: 7,
    prodname: "Printed Collared Formal Shirt",
    price: 5099,
    originalPrice: 6899,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Back",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Collared",
    pattern: "Printed",
    rating: 4.1,
    reviews: 92,
    description:
      "Elegant printed formal shirt for office and business meetings.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sky Blue"],
    inStock: true,
  },
  {
    id: 8,
    prodname: "Embroidered Ethnic Kurta",
    price: 8299,
    originalPrice: 10499,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Ethnic+Kurta",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Kurta",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Kurta",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Boat Neck",
    pattern: "Embroidered",
    rating: 4.7,
    reviews: 103,
    description: "Richly embroidered traditional kurta for festive occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "Royal Blue"],
    inStock: true,
  },
  {
    id: 9,
    prodname: "Party Wear V-Neck Top",
    price: 4599,
    originalPrice: 5799,
    image: "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Design",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "V-Neck",
    pattern: "Solid",
    rating: 4.3,
    reviews: 80,
    description: "Stylish party wear top with a flattering v-neck pattern.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Red"],
    inStock: true,
  },
  {
    id: 10,
    prodname: "Casual Round Neck Tee",
    price: 2499,
    originalPrice: 3499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Casual+Round+Neck+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Side",
    ],
    category: "kids",
    sleeveType: "Short Sleeve",
    neckType: "Round Neck",
    pattern: "Solid",
    rating: 4.2,
    reviews: 145,
    description: "Comfortable and breathable everyday wear tee.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Green"],
    inStock: true,
  },
  {
    id: 11,
    prodname: "Sporty Sleeveless Vest",
    price: 1999,
    originalPrice: 2999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sport+Vest",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "Round Neck",
    pattern: "Solid",
    rating: 4.0,
    reviews: 60,
    description: "Perfect vest for workouts and gym wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue"],
    inStock: true,
  },
  {
    id: 12,
    prodname: "Ethnic Printed Shirt",
    price: 6899,
    originalPrice: 8899,
    image: "https://dummyimage.com/400x400/ccc/000&text=Printed+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Ethnic",
      "https://dummyimage.com/400x400/ccc/000&text=Detail",
    ],
    category: "men",
    sleeveType: "Short Sleeve",
    neckType: "Round Neck",
    pattern: "Printed",
    rating: 4.6,
    reviews: 115,
    description: "Traditional ethnic shirt with vibrant printed patterns.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Yellow", "Green"],
    inStock: true,
  },

  {
    id: 13,
    prodname: "Sleeveless Checked Casual Top",
    price: 3899,
    originalPrice: 4799,
    image: "https://dummyimage.com/400x400/ccc/000&text=Checked+Casual+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Zoom",
    ],
    category: "men",
    sleeveType: "Sleeveless",
    neckType: "Round Neck",
    pattern: "Checked",
    rating: 4.1,
    reviews: 76,
    description: "Smart and stylish sleeveless casual top.",
    sizes: ["XS", "S", "M"],
    colors: ["Pink", "White"],
    inStock: true,
  },
  {
    id: 14,
    prodname: "Formal Long Sleeve Solid Shirt",
    price: 6199,
    originalPrice: 7299,
    image: "https://dummyimage.com/400x400/ccc/000&text=Formal+Solid+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Collared",
    pattern: "Solid",
    rating: 4.4,
    reviews: 121,
    description: "Classic formal wear shirt for office professionals.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["White", "Blue"],
    inStock: true,
  },
  {
    id: 15,
    prodname: "Party Checked Shirt with V-Neck",
    price: 5499,
    originalPrice: 6499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Party+Checked+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Vneck",
      "https://dummyimage.com/400x400/ccc/000&text=Details",
    ],
    category: "men",
    sleeveType: "Short Sleeve",
    neckType: "V-Neck",
    pattern: "Checked",
    rating: 4.0,
    reviews: 87,
    description: "Trendy checked v-neck shirt for party nights.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Black"],
    inStock: true,
  },
  {
    id: 16,
    prodname: "Boat Neck Embroidered Ethnic Top",
    price: 7999,
    originalPrice: 9999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Boat+Neck+Ethnic+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Embroidery",
    ],
    category: "men",
    sleeveType: "Long Sleeve",
    neckType: "Boat Neck",
    pattern: "Embroidered",
    rating: 4.9,
    reviews: 148,
    description: "Exquisite boat neck ethnic top with fine embroidery.",
    sizes: ["S", "M", "L"],
    colors: ["Maroon", "Gold"],
    inStock: true,
  },
  {
    id: 17,
    prodname: "Solid Collared Sports Tee",
    price: 3699,
    originalPrice: 4599,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sports+Collared+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Tee",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Tee",
    ],
    category: "men",
    sleeveType: "Short Sleeve",
    neckType: "Collared",
    pattern: "Solid",
    rating: 4.3,
    reviews: 99,
    description: "Comfortable collared t-shirt for athletic wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Navy"],
    inStock: true,
  },
  {
    id: 18,
    prodname: "Sleeveless Party Embroidered Top",
    price: 4799,
    originalPrice: 6199,
    image: "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Design",
    ],
    category: "women",
    sleeveType: "Sleeveless",
    neckType: "Round Neck",
    pattern: "Embroidered",
    rating: 4.5,
    reviews: 134,
    description: "Beautiful embroidered top for evening parties.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Silver"],
    inStock: true,
  },
];
