export const mockProducts = [
  {
    id: 1,
    name: "Embroidered Long Sleeve Sports Shirt",
    price: 6820,
    originalPrice: 8830,
    image: "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
      "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/30220263/2024/7/14/84aa150c-3151-4513-9424-1150f99656211720935744276FREECULTRMen2HoodedOrganicCottonPocketsT-shirt1.jpg",
    ],
    category: "Sports",
    type: "Long Sleeve",
    neckStyle: "Collared",
    design: "Embroidered",
    rating: 4.8,
    reviews: 127,
    description:
      "A high-quality embroidered long sleeve shirt suitable for sports occasions.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Emerald", "Green", "Gray"],
    inStock: true,
  },
  {
    id: 2,
    name: "Checked Sleeveless Casual Shirt",
    price: 7849,
    originalPrice: 9065,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    ],
    category: "Casual",
    type: "Sleeveless",
    neckStyle: "Round Neck",
    design: "Checked",
    rating: 4.0,
    reviews: 128,
    description:
      "A high-quality checked sleeveless shirt suitable for casual occasions.",
    sizes: ["XS", "XL", "XXL", "M", "S", "L"],
    colors: ["Gold", "Silver", "White"],
    inStock: true,
  },
  {
    id: 3,
    name: "Striped Short Sleeve Ethnic Shirt",
    price: 5628,
    originalPrice: 7883,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    ],
    category: "Ethnic",
    type: "Short Sleeve",
    neckStyle: "V-Neck",
    design: "Striped",
    rating: 4.0,
    reviews: 295,
    description:
      "A high-quality striped short sleeve shirt suitable for ethnic occasions.",
    sizes: ["XS", "S", "M", "XL", "L", "XXL"],
    colors: ["Pink", "Blue", "Emerald"],
    inStock: true,
  },
  {
    id: 4,
    name: "Checked Sleeveless Formal Shirt",
    price: 4396,
    originalPrice: 5609,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    ],
    category: "Formal",
    type: "Sleeveless",
    neckStyle: "Round Neck",
    design: "Checked",
    rating: 4.6,
    reviews: 239,
    description:
      "A high-quality checked sleeveless shirt suitable for formal occasions.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Gray", "Pink"],
    inStock: true,
  },
  {
    id: 5,
    name: "Solid Boat Neck Ethnic Shirt",
    price: 5210,
    originalPrice: 7876,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    ],
    category: "Ethnic",
    type: "Sleeveless",
    neckStyle: "Boat Neck",
    design: "Solid",
    rating: 4.2,
    reviews: 62,
    description:
      "A high-quality solid sleeveless shirt suitable for ethnic occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Maroon", "Royal Blue", "Black"],
    inStock: true,
  },
  {
    id: 6,
    name: "Printed Long Sleeve Party Shirt",
    price: 6159,
    originalPrice: 7655,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    ],
    category: "Party",
    type: "Long Sleeve",
    neckStyle: "Collared",
    design: "Printed",
    rating: 4.5,
    reviews: 177,
    description:
      "A high-quality printed long sleeve shirt suitable for party occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "White", "Black"],
    inStock: true,
  },

  {
    id: 7,
    name: "Printed Collared Formal Shirt",
    price: 5099,
    originalPrice: 6899,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Back",
    ],
    category: "Formal",
    type: "Long Sleeve",
    neckStyle: "Collared",
    design: "Printed",
    rating: 4.1,
    reviews: 92,
    description:
      "Elegant printed formal shirt for office and business meetings.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sky Blue"],
    inStock: true,
  },
  {
    id: 8,
    name: "Embroidered Ethnic Kurta",
    price: 8299,
    originalPrice: 10499,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Ethnic+Kurta",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Kurta",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Kurta",
    ],
    category: "Ethnic",
    type: "Long Sleeve",
    neckStyle: "Boat Neck",
    design: "Embroidered",
    rating: 4.7,
    reviews: 103,
    description: "Richly embroidered traditional kurta for festive occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "Royal Blue"],
    inStock: true,
  },
  {
    id: 9,
    name: "Party Wear V-Neck Top",
    price: 4599,
    originalPrice: 5799,
    image: "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Design",
    ],
    category: "Party",
    type: "Sleeveless",
    neckStyle: "V-Neck",
    design: "Solid",
    rating: 4.3,
    reviews: 80,
    description: "Stylish party wear top with a flattering v-neck design.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Red"],
    inStock: true,
  },
  {
    id: 10,
    name: "Casual Round Neck Tee",
    price: 2499,
    originalPrice: 3499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Casual+Round+Neck+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Side",
    ],
    category: "Casual",
    type: "Short Sleeve",
    neckStyle: "Round Neck",
    design: "Solid",
    rating: 4.2,
    reviews: 145,
    description: "Comfortable and breathable everyday wear tee.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Green"],
    inStock: true,
  },
  {
    id: 11,
    name: "Sporty Sleeveless Vest",
    price: 1999,
    originalPrice: 2999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sport+Vest",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "Sports",
    type: "Sleeveless",
    neckStyle: "Round Neck",
    design: "Solid",
    rating: 4.0,
    reviews: 60,
    description: "Perfect vest for workouts and gym wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue"],
    inStock: true,
  },
  {
    id: 12,
    name: "Ethnic Printed Shirt",
    price: 6899,
    originalPrice: 8899,
    image: "https://dummyimage.com/400x400/ccc/000&text=Printed+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Ethnic",
      "https://dummyimage.com/400x400/ccc/000&text=Detail",
    ],
    category: "Ethnic",
    type: "Short Sleeve",
    neckStyle: "Round Neck",
    design: "Printed",
    rating: 4.6,
    reviews: 115,
    description: "Traditional ethnic shirt with vibrant printed patterns.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Yellow", "Green"],
    inStock: true,
  },

  {
    id: 13,
    name: "Sleeveless Checked Casual Top",
    price: 3899,
    originalPrice: 4799,
    image: "https://dummyimage.com/400x400/ccc/000&text=Checked+Casual+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Zoom",
    ],
    category: "Casual",
    type: "Sleeveless",
    neckStyle: "Round Neck",
    design: "Checked",
    rating: 4.1,
    reviews: 76,
    description: "Smart and stylish sleeveless casual top.",
    sizes: ["XS", "S", "M"],
    colors: ["Pink", "White"],
    inStock: true,
  },
  {
    id: 14,
    name: "Formal Long Sleeve Solid Shirt",
    price: 6199,
    originalPrice: 7299,
    image: "https://dummyimage.com/400x400/ccc/000&text=Formal+Solid+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "Formal",
    type: "Long Sleeve",
    neckStyle: "Collared",
    design: "Solid",
    rating: 4.4,
    reviews: 121,
    description: "Classic formal wear shirt for office professionals.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["White", "Blue"],
    inStock: true,
  },
  {
    id: 15,
    name: "Party Checked Shirt with V-Neck",
    price: 5499,
    originalPrice: 6499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Party+Checked+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Vneck",
      "https://dummyimage.com/400x400/ccc/000&text=Details",
    ],
    category: "Party",
    type: "Short Sleeve",
    neckStyle: "V-Neck",
    design: "Checked",
    rating: 4.0,
    reviews: 87,
    description: "Trendy checked v-neck shirt for party nights.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Black"],
    inStock: true,
  },
  {
    id: 16,
    name: "Boat Neck Embroidered Ethnic Top",
    price: 7999,
    originalPrice: 9999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Boat+Neck+Ethnic+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Embroidery",
    ],
    category: "Ethnic",
    type: "Long Sleeve",
    neckStyle: "Boat Neck",
    design: "Embroidered",
    rating: 4.9,
    reviews: 148,
    description: "Exquisite boat neck ethnic top with fine embroidery.",
    sizes: ["S", "M", "L"],
    colors: ["Maroon", "Gold"],
    inStock: true,
  },
  {
    id: 17,
    name: "Solid Collared Sports Tee",
    price: 3699,
    originalPrice: 4599,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sports+Collared+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Tee",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Tee",
    ],
    category: "Sports",
    type: "Short Sleeve",
    neckStyle: "Collared",
    design: "Solid",
    rating: 4.3,
    reviews: 99,
    description: "Comfortable collared t-shirt for athletic wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Navy"],
    inStock: true,
  },
  {
    id: 18,
    name: "Sleeveless Party Embroidered Top",
    price: 4799,
    originalPrice: 6199,
    image: "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Design",
    ],
    category: "Party",
    type: "Sleeveless",
    neckStyle: "Round Neck",
    design: "Embroidered",
    rating: 4.5,
    reviews: 134,
    description: "Beautiful embroidered top for evening parties.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Silver"],
    inStock: true,
  },
];
export const mockProductscopy = [
  {
    _id: 1,
    prodname: "Embroidered Long Sleeve Sports Shirt",
    price: 6820,
    originalPrice: 8830,
    image: "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
      "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/30220263/2024/7/14/84aa150c-3151-4513-9424-1150f99656211720935744276FREECULTRMen2HoodedOrganicCottonPocketsT-shirt1.jpg",
    ],
    category: "Sports",
    type: "Long Sleeve",
    neckType: "Collared",
    design: "Embroidered",
    fit: 4.8,
    fabric: 127,
    description:
      "A high-quality embroidered long sleeve shirt suitable for sports occasions.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Emerald", "Green", "Gray"],
    occasion: true,
  },
  {
    _id: 2,
    prodname: "Checked Sleeveless Casual Shirt",
    price: 7849,
    originalPrice: 9065,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Casual+Shirt",
    ],
    category: "Casual",
    type: "Sleeveless",
    neckType: "Round Neck",
    design: "Checked",
    fit: 4.0,
    fabric: 128,
    description:
      "A high-quality checked sleeveless shirt suitable for casual occasions.",
    sizes: ["XS", "XL", "XXL", "M", "S", "L"],
    colors: ["Gold", "Silver", "White"],
    occasion: true,
  },
  {
    _id: 3,
    prodname: "Striped Short Sleeve Ethnic Shirt",
    price: 5628,
    originalPrice: 7883,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Striped+Short+Sleeve+Ethnic+Shirt",
    ],
    category: "Ethnic",
    type: "Short Sleeve",
    neckType: "V-Neck",
    design: "Striped",
    fit: 4.0,
    fabric: 295,
    description:
      "A high-quality striped short sleeve shirt suitable for ethnic occasions.",
    sizes: ["XS", "S", "M", "XL", "L", "XXL"],
    colors: ["Pink", "Blue", "Emerald"],
    occasion: true,
  },
  {
    _id: 4,
    prodname: "Checked Sleeveless Formal Shirt",
    price: 4396,
    originalPrice: 5609,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Sleeveless+Formal+Shirt",
    ],
    category: "Formal",
    type: "Sleeveless",
    neckType: "Round Neck",
    design: "Checked",
    fit: 4.6,
    fabric: 239,
    description:
      "A high-quality checked sleeveless shirt suitable for formal occasions.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Gray", "Pink"],
    occasion: true,
  },
  {
    _id: 5,
    prodname: "Solid Boat Neck Ethnic Shirt",
    price: 5210,
    originalPrice: 7876,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Solid+Boat+Neck+Ethnic+Shirt",
    ],
    category: "Ethnic",
    type: "Sleeveless",
    neckType: "Boat Neck",
    design: "Solid",
    fit: 4.2,
    fabric: 62,
    description:
      "A high-quality solid sleeveless shirt suitable for ethnic occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Maroon", "Royal Blue", "Black"],
    occasion: true,
  },
  {
    _id: 6,
    prodname: "Printed Long Sleeve Party Shirt",
    price: 6159,
    originalPrice: 7655,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Long+Sleeve+Party+Shirt",
    ],
    category: "Party",
    type: "Long Sleeve",
    neckType: "Collared",
    design: "Printed",
    fit: 4.5,
    fabric: 177,
    description:
      "A high-quality printed long sleeve shirt suitable for party occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "White", "Black"],
    occasion: true,
  },

  {
    _id: 7,
    prodname: "Printed Collared Formal Shirt",
    price: 5099,
    originalPrice: 6899,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Collared+Formal+Shirt",
      "https://dummyimage.com/400x400/ccc/000&text=Printed+Back",
    ],
    category: "Formal",
    type: "Long Sleeve",
    neckType: "Collared",
    design: "Printed",
    fit: 4.1,
    fabric: 92,
    description:
      "Elegant printed formal shirt for office and business meetings.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sky Blue"],
    occasion: true,
  },
  {
    _id: 8,
    prodname: "Embroidered Ethnic Kurta",
    price: 8299,
    originalPrice: 10499,
    image:
      "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Ethnic+Kurta",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Kurta",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Kurta",
    ],
    category: "Ethnic",
    type: "Long Sleeve",
    neckType: "Boat Neck",
    design: "Embroidered",
    fit: 4.7,
    fabric: 103,
    description: "Richly embroidered traditional kurta for festive occasions.",
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "Royal Blue"],
    occasion: true,
  },
  {
    _id: 9,
    prodname: "Party Wear V-Neck Top",
    price: 4599,
    originalPrice: 5799,
    image: "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=V-Neck+Party+Top",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Design",
    ],
    category: "Party",
    type: "Sleeveless",
    neckType: "V-Neck",
    design: "Solid",
    fit: 4.3,
    fabric: 80,
    description: "Stylish party wear top with a flattering v-neck design.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Red"],
    occasion: true,
  },
  {
    _id: 10,
    prodname: "Casual Round Neck Tee",
    price: 2499,
    originalPrice: 3499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Casual+Round+Neck+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Side",
    ],
    category: "Casual",
    type: "Short Sleeve",
    neckType: "Round Neck",
    design: "Solid",
    fit: 4.2,
    fabric: 145,
    description: "Comfortable and breathable everyday wear tee.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Green"],
    occasion: true,
  },
  {
    _id: 11,
    prodname: "Sporty Sleeveless Vest",
    price: 1999,
    originalPrice: 2999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sport+Vest",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "Sports",
    type: "Sleeveless",
    neckType: "Round Neck",
    design: "Solid",
    fit: 4.0,
    fabric: 60,
    description: "Perfect vest for workouts and gym wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue"],
    occasion: true,
  },
  {
    _id: 12,
    prodname: "Ethnic Printed Shirt",
    price: 6899,
    originalPrice: 8899,
    image: "https://dummyimage.com/400x400/ccc/000&text=Printed+Ethnic+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Ethnic",
      "https://dummyimage.com/400x400/ccc/000&text=Detail",
    ],
    category: "Ethnic",
    type: "Short Sleeve",
    neckType: "Round Neck",
    design: "Printed",
    fit: 4.6,
    fabric: 115,
    description: "Traditional ethnic shirt with vibrant printed patterns.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Yellow", "Green"],
    occasion: true,
  },

  {
    _id: 13,
    prodname: "Sleeveless Checked Casual Top",
    price: 3899,
    originalPrice: 4799,
    image: "https://dummyimage.com/400x400/ccc/000&text=Checked+Casual+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Zoom",
    ],
    category: "Casual",
    type: "Sleeveless",
    neckType: "Round Neck",
    design: "Checked",
    fit: 4.1,
    fabric: 76,
    description: "Smart and stylish sleeveless casual top.",
    sizes: ["XS", "S", "M"],
    colors: ["Pink", "White"],
    occasion: true,
  },
  {
    _id: 14,
    prodname: "Formal Long Sleeve Solid Shirt",
    price: 6199,
    originalPrice: 7299,
    image: "https://dummyimage.com/400x400/ccc/000&text=Formal+Solid+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Back",
    ],
    category: "Formal",
    type: "Long Sleeve",
    neckType: "Collared",
    design: "Solid",
    fit: 4.4,
    fabric: 121,
    description: "Classic formal wear shirt for office professionals.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["White", "Blue"],
    occasion: true,
  },
  {
    _id: 15,
    prodname: "Party Checked Shirt with V-Neck",
    price: 5499,
    originalPrice: 6499,
    image: "https://dummyimage.com/400x400/ccc/000&text=Party+Checked+Shirt",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Checked+Vneck",
      "https://dummyimage.com/400x400/ccc/000&text=Details",
    ],
    category: "Party",
    type: "Short Sleeve",
    neckType: "V-Neck",
    design: "Checked",
    fit: 4.0,
    fabric: 87,
    description: "Trendy checked v-neck shirt for party nights.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Black"],
    occasion: true,
  },
  {
    _id: 16,
    prodname: "Boat Neck Embroidered Ethnic Top",
    price: 7999,
    originalPrice: 9999,
    image: "https://dummyimage.com/400x400/ccc/000&text=Boat+Neck+Ethnic+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Embroidery",
    ],
    category: "Ethnic",
    type: "Long Sleeve",
    neckType: "Boat Neck",
    design: "Embroidered",
    fit: 4.9,
    fabric: 148,
    description: "Exquisite boat neck ethnic top with fine embroidery.",
    sizes: ["S", "M", "L"],
    colors: ["Maroon", "Gold"],
    occasion: true,
  },
  {
    _id: 17,
    prodname: "Solid Collared Sports Tee",
    price: 3699,
    originalPrice: 4599,
    image: "https://dummyimage.com/400x400/ccc/000&text=Sports+Collared+Tee",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front+Tee",
      "https://dummyimage.com/400x400/ccc/000&text=Back+Tee",
    ],
    category: "Sports",
    type: "Short Sleeve",
    neckType: "Collared",
    design: "Solid",
    fit: 4.3,
    fabric: 99,
    description: "Comfortable collared t-shirt for athletic wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Navy"],
    occasion: true,
  },
  {
    _id: 18,
    prodname: "Sleeveless Party Embroidered Top",
    price: 4799,
    originalPrice: 6199,
    image: "https://dummyimage.com/400x400/ccc/000&text=Embroidered+Party+Top",
    images: [
      "https://dummyimage.com/400x400/ccc/000&text=Front",
      "https://dummyimage.com/400x400/ccc/000&text=Design",
    ],
    category: "Party",
    type: "Sleeveless",
    neckType: "Round Neck",
    design: "Embroidered",
    fit: "Slim",
    fabric: 134,
    description: "Beautiful embroidered top for evening parties.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Silver"],
    occasion: true,
  },
];
export const mockOrders = [
  {
    id: "ORD-001",
    date: "2024-01-15",
    status: "Delivered",
    total: 129.97,
    items: [
      { id: 1, name: "Classic Cotton T-Shirt", quantity: 2, price: 2999 },
      { id: 2, name: "Formal Button-Down Shirt", quantity: 1, price: 5999 },
    ],
  },
  {
    id: "ORD-002",
    date: "2024-01-20",
    status: "Shipped",
    total: 89.99,
    items: [{ id: 3, name: "Party Sequin Top", quantity: 1, price: 8999 }],
  },
];

export const mockUsers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "user",
    joinDate: "2023-12-01",
    orders: 5,
    totalSpent: 29995,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    role: "user",
    joinDate: "2023-11-15",
    orders: 3,
    totalSpent: 18997,
  },
];

export const sizes = ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL"];
export const fits = ["Slim", "Regular", "Relaxed", "Loose"];
export const categories = ["men", "women", "kids", "unisex"];
export const occasions = ["Casual", "Formal", "Party", "Sports", "Ethnic"];
export const patterns = [
  "Solid",
  "Printed",
  "Striped",
  "Checked",
  "Embroidered",
  "Lace",
  "Floral",
];
export const neckTypes = ["Round Neck", "V-Neck", "Collared", "Boat Neck"];
export const sleeveTypes = [
  "Sleeveless",
  "Short Sleeve",
  "Three-Quarter Sleeves",
  "Long Sleeve",
];
